apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: static-web-hpa
  namespace: static-site-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: static-web
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
