apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pvc
spec:
  capacity:
    storage: 1Gi              # ✅ Este campo tiene que estar así, exactamente
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # 👈 Este valor debe coincidir con el PVC
  hostPath:
    path: "/mnt/static-website"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: static-site-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: static-pvc
