apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  namespace: static-site-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/static-website"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: static-site-ns
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: static-pv  # Vincula el PVC al PV manual